// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru_RU.po' and run '.po' extractor
export const events = {
  'examples.hierarchical.events.title': 'Название события',
};
