// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru_RU.po' and run '.po' extractor
import { events } from './events';
import { base } from './base';

export const ru_RU = {
  ...events,
  ...base,

  'examples.flat.example.1': 'Пример 1',
  'examples.flat.example.2': 'Пример 2 {foo}',
};
