// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/en_US.po' and run '.po' extractor
export const base = {
  'examples.hierarchical.example.1': 'Example 1',
  'examples.hierarchical.example.2': 'Example 2',
};
