// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/en_US.po' and run '.po' extractor
export const events = {
  'examples.hierarchical.events.title': 'Event name',
};
