// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/en_US.po' and run '.po' extractor
import { base } from './base';
import { events } from './events';

export const en_US = {
  ...base,
  ...events,

  'examples.flat.example.1': 'Example 1',
  'examples.flat.example.2': 'Example 2 {foo}',
};
