name: Deployments

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
