name: Deployments

on:
  push:
    branches:
      - main
      - "#11"

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn run build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Get package version
        id: get_version
        env:
          VERSION: ${{ steps.publish.outputs.id }}
        run: echo "::set-output name=fragment::${VERSION##*@}"

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.fragment }}
